language: java
sudo: false

jdk:
  - oraclejdk8
  - openjdk7

branches:
  only:
    - master



before_script:
  - cp -f -r ~/.ekstazi ./

script:
  - mvn -Pekstazi test
  - pwd
  - find -name .ekstazi
  - cp -f -r ./.ekstazi ~

cache:
  directories:
  - ~/.ekstazi
